// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601181900_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExternalRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalRef")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DefaultProbability")
                        .HasColumnType("double precision");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<decimal>("BillAmt1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BillAmt2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BillAmt3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BillAmt4")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BillAmt5")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BillAmt6")
                        .HasColumnType("numeric");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("Education")
                        .HasColumnType("integer");

                    b.Property<int>("LimitBal")
                        .HasColumnType("integer");

                    b.Property<int>("Marriage")
                        .HasColumnType("integer");

                    b.Property<int>("Pay0")
                        .HasColumnType("integer");

                    b.Property<int>("Pay2")
                        .HasColumnType("integer");

                    b.Property<int>("Pay3")
                        .HasColumnType("integer");

                    b.Property<int>("Pay4")
                        .HasColumnType("integer");

                    b.Property<int>("Pay5")
                        .HasColumnType("integer");

                    b.Property<int>("Pay6")
                        .HasColumnType("integer");

                    b.Property<decimal>("PayAmt1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PayAmt2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PayAmt3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PayAmt4")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PayAmt5")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PayAmt6")
                        .HasColumnType("numeric");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "SnapshotDate");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Trend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alert")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Slope")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "ModelName");

                    b.ToTable("Trends");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Prediction", b =>
                {
                    b.HasOne("WebApi.Models.Entities.Snapshot", "Snapshot")
                        .WithMany("Predictions")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Snapshot", b =>
                {
                    b.HasOne("WebApi.Models.Entities.Client", "Client")
                        .WithMany("Snapshots")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Trend", b =>
                {
                    b.HasOne("WebApi.Models.Entities.Client", "Client")
                        .WithMany("Trends")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Client", b =>
                {
                    b.Navigation("Snapshots");

                    b.Navigation("Trends");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Snapshot", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
